# Generated by Django 4.1.4 on 2023-01-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='La_tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('slogan', models.CharField(max_length=170)),
                ('regle', models.CharField(max_length=70)),
            ],
        ),
    ]
